name: gardeniapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  get: 4.6.6
  intl: ^0.18.0

dev_dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  flashy_tab_bar2: ^0.0.10
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  flutter_test:
    sdk: flutter
  intl: ^0.18.1
  staggered_grid_view_flutter: ^0.0.4
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterLight.ttf
          weight: 300
    - family: Merriweather
      fonts:
        - asset: assets/fonts/MerriweatherBold.ttf
          weight: 700
        - asset: assets/fonts/MerriweatherBlack.ttf
          weight: 900
        - asset: assets/fonts/MerriweatherRegular.ttf
          weight: 400
        - asset: assets/fonts/MerriweatherLight.ttf
          weight: 300
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
